import { describe, it, expect } from "vitest";
import { criterionChanges, parseChecklistString } from "./checklist";

/**
 * One parser, three writers: acceptance criteria are typed by hand in `TaskForm`, generated by
 * the AI route, and sent over MCP as `acceptanceCriteria`. None of them agrees on a spelling, so
 * everything below is a shape that has actually arrived.
 */
describe("parseChecklistString", () => {
  it("reads a markdown checklist", () => {
    expect(parseChecklistString("- [ ] first\n- [x] second")).toEqual([
      { text: "first", done: false },
      { text: "second", done: true },
    ]);
  });

  it("accepts either bullet character and either case of the tick", () => {
    expect(parseChecklistString("* [X] starred\n- [x] dashed")).toEqual([
      { text: "starred", done: true },
      { text: "dashed", done: true },
    ]);
  });

  // A bullet with no box is an item nobody has ticked, not a line to drop: the AI route writes
  // plain bullets and a person pasting a list writes them too.
  it("treats a bullet with no box as an unticked item", () => {
    expect(parseChecklistString("- just a bullet")).toEqual([
      { text: "just a bullet", done: false },
    ]);
  });

  it("treats a bare line as an unticked item", () => {
    expect(parseChecklistString("no bullet at all")).toEqual([
      { text: "no bullet at all", done: false },
    ]);
  });

  it("drops blank lines rather than storing empty criteria", () => {
    expect(parseChecklistString("- [ ] first\n\n   \n- [ ] second")).toHaveLength(2);
  });

  it("trims the line and the text inside it", () => {
    expect(parseChecklistString("   - [ ]   padded   ")).toEqual([
      { text: "padded", done: false },
    ]);
  });

  it.each([
    ["an empty string", ""],
    ["only whitespace", "   \n  \n"],
  ])("answers with nothing for %s", (_name, value) => {
    expect(parseChecklistString(value)).toEqual([]);
  });

  // The MCP tool's argument is typed but not validated at the boundary, and the AI route's answer
  // is parsed JSON, so a non-string does reach this.
  it.each([
    ["null", null],
    ["undefined", undefined],
    ["a number", 7],
    ["an object", { text: "x" }],
  ])("answers with nothing for %s rather than throwing", (_name, value) => {
    expect(parseChecklistString(value as unknown as string)).toEqual([]);
  });

  /**
   * A box with anything other than a space or an x in it is not a checkbox — it is text that
   * happens to start with a bracket, and the whole line is kept. Reading `- [-] item` as an item
   * called "item" would silently drop the `-` somebody typed.
   */
  it("keeps a line whose box holds something that is not a tick", () => {
    expect(parseChecklistString("- [-] partly done")).toEqual([
      { text: "[-] partly done", done: false },
    ]);
  });

  it("keeps a box with no text after it as a plain line", () => {
    expect(parseChecklistString("- [ ]")).toEqual([{ text: "[ ]", done: false }]);
  });

  // Only the first box on a line is the checkbox; the rest is the item's own text, brackets and
  // all. A criterion that mentions another checklist keeps what it said.
  it("reads only the leading box, and leaves any later one in the text", () => {
    expect(parseChecklistString("- [x] done, unlike - [ ] the other one")).toEqual([
      { text: "done, unlike - [ ] the other one", done: true },
    ]);
  });

  it("handles a Windows line ending, which the trim removes", () => {
    expect(parseChecklistString("- [ ] first\r\n- [x] second")).toEqual([
      { text: "first", done: false },
      { text: "second", done: true },
    ]);
  });
});

describe("criterionChanges", () => {
  const c = (_id: string, text: string, done = false) => ({ _id, text, done });

  it("says nothing about a list that did not change", () => {
    expect(criterionChanges([c("a", "One"), c("b", "Two", true)], [c("a", "One"), c("b", "Two", true)])).toEqual([]);
  });

  it("names an added and a removed criterion by their text", () => {
    expect(criterionChanges([c("a", "One"), c("b", "Two")], [c("a", "One"), c("n", "Three")])).toEqual([
      { action: "criterion_removed", id: "b", before: "Two", after: "" },
      { action: "criterion_added", id: "n", before: "", after: "Three" },
    ]);
  });

  it("tells ticking from unticking", () => {
    expect(criterionChanges([c("a", "One"), c("b", "Two", true)], [c("a", "One", true), c("b", "Two")])).toEqual([
      { action: "criterion_checked", id: "a", before: "", after: "One" },
      { action: "criterion_unchecked", id: "b", before: "", after: "Two" },
    ]);
  });

  it("reads a changed text on the same id as an edit, not a removal and an addition", () => {
    expect(criterionChanges([c("a", "One")], [c("a", "One, reworded", true)])).toEqual([
      { action: "criterion_edited", id: "a", before: "One", after: "One, reworded" },
      { action: "criterion_checked", id: "a", before: "", after: "One, reworded" },
    ]);
  });

  // MCP and the AI path send the whole list as text, so every row comes back under a fresh id
  it("matches a re-minted row to the one it replaced by its text", () => {
    const before = [c("a", "One"), c("b", "Two")];
    const after = [c("x", "One", true), c("y", "Two")];
    expect(criterionChanges(before, after)).toEqual([
      { action: "criterion_checked", id: "x", before: "", after: "One" },
    ]);
  });

  it("pairs duplicate texts one to one", () => {
    expect(criterionChanges([c("a", "Same")], [c("x", "Same"), c("y", "Same")])).toEqual([
      { action: "criterion_added", id: "y", before: "", after: "Same" },
    ]);
  });

  it("prefers the id over a text match", () => {
    const before = [c("a", "One"), c("b", "Two")];
    const after = [c("b", "One"), c("x", "One")];
    expect(criterionChanges(before, after)).toEqual([
      { action: "criterion_edited", id: "b", before: "Two", after: "One" },
    ]);
  });
});
